version: '3.8'
services:
  frontend:
    build:
      context: ./react-ui-lib/react/mireactapp
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - ./react-ui-lib/react/mireactapp/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./react-ui-lib/react/mireactapp:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build:
      context: ./express.js
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - ./express.js/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./express.js:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./express.js/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./express.js/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
